<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>XXTCC</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="b0494a1f-4bd3-9uSlsI0ujng92WU1fp-T5w--" />
    <None Remove="b0494a1f-4bd3-h8G0WumVD1E-YmVqGx0StA--" />
    <None Remove="b0494a1f-4bd3-wL5fq2CjqZ-7URzizFyXFQ--" />
    <None Remove="b0494a1f-4bd3-rXuzzA4DuzdpoFQY1YsYOQ--" />
    <None Remove="b0494a1f-4bd3--2HLZ30k7H3wekWNmp-iuA--" />
    <None Remove="b0494a1f-4bd3-NMd8IvH6RWX.USFHchM3PA--" />
    <None Remove="b0494a1f-4bd3-Zl7jbAhgSrPgNEcLo0Sg9A--" />
    <EmbeddedResource Include="b0494a1f-4bd3-9uSlsI0ujng92WU1fp-T5w--" LogicalName="b0494a1f-4bd3-9uSlsI0ujng92WU1fp+T5w==" />
    <EmbeddedResource Include="b0494a1f-4bd3-h8G0WumVD1E-YmVqGx0StA--" LogicalName="b0494a1f-4bd3-h8G0WumVD1E+YmVqGx0StA==" />
    <EmbeddedResource Include="b0494a1f-4bd3-wL5fq2CjqZ-7URzizFyXFQ--" LogicalName="b0494a1f-4bd3-wL5fq2CjqZ+7URzizFyXFQ==" />
    <EmbeddedResource Include="b0494a1f-4bd3-rXuzzA4DuzdpoFQY1YsYOQ--" LogicalName="b0494a1f-4bd3-rXuzzA4DuzdpoFQY1YsYOQ==" />
    <EmbeddedResource Include="b0494a1f-4bd3--2HLZ30k7H3wekWNmp-iuA--" LogicalName="b0494a1f-4bd3-+2HLZ30k7H3wekWNmp+iuA==" />
    <EmbeddedResource Include="b0494a1f-4bd3-NMd8IvH6RWX.USFHchM3PA--" LogicalName="b0494a1f-4bd3-NMd8IvH6RWX/USFHchM3PA==" />
    <EmbeddedResource Include="b0494a1f-4bd3-Zl7jbAhgSrPgNEcLo0Sg9A--" LogicalName="b0494a1f-4bd3-Zl7jbAhgSrPgNEcLo0Sg9A==" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Data" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="Renci.SshNet" />
    <Reference Include="WebSocket4Net" />
    <Reference Include="Nancy.Hosting.Self" />
    <Reference Include="Nancy" />
    <Reference Include="System.Web" />
    <Reference Include="MyXls.SL2" />
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>